server:
  port: 8002

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1 # 值介于0和1之间：0不发送任何数据；0.5发送50%的数据

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
