server:
  port: 5555

spring:
  application:
    name: zuul-service
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  # 忽略Eureka自动获取id
  ignoredServices: '*'
  routes:
    user-service: /user/**
  # 所有应用部署在一台服务器（正常配置时间是1秒）
  semaphore:
    max-semaphores: 6000
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

## 所有应用部署在一台服务器（正常配置时间是1秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 6000
          ribbon:
            ReadTimeout: 6000
            ConnectTimeout: 6000